### PR TITLE
feat(soft-io-exit): New control pipe command to io-detach if GA is down

### LINKED ISSUE #111: Semi-Temporarily switch the input to windows
If you have BitLocker enabled, you obviously need to switch over your keyboard to Windows to enter your password. 

During the boot of Windows both Windows and Linux are blocked. This is usually not a problem, as the Windows boot is less than 10 seconds for me, and waiting isn't a big problem. However, Windows Update can prolongen this time where I can neither use windows nor linux significantly. 

This is the reason I usually use a second hotkey, executing this script when booting:

```bash
#!/bin/bash
echo -e -n '\x03' | netcat -w 1 -U /run/user/1000/windows-gaming-driver/control.sock
sleep 20
echo -e -n '\x04' | netcat -w 1 -U /run/user/1000/windows-gaming-driver/control.sock
```

This script exits the IO-devices again after 20 seconds, so if Windows Update takes longer, I can use Linux again. 

However, I'd like to propose an aditional command besides `IoExit`: `SoftIoExit` - it only exits when the guest agent isn't active at the moment - similar to `IoEntry` and `ForceIoEntry`, but vice versa. This has some advantages:

- The way I hand over my IO-devices is consitent, I'd only have one hotkey instead of two. If the GA isn't running for some reason, the controls will be handed back to linux after a while.
- If I boot fast there is no unnecessary entry / exit. 
- I can't make a mistake when pressing the hotkey.

### PR DESCRIPTION
**Pull request by oberien**
Fix #111

### CODE REVIEW

**Comment by main--** [comment]
Is there any reason at all to have this once #92 is done? It clearly resolves #111 as well, in a much better way.

**Comment by oberien** [comment]
If Linux has a keylogger, it'll log the password in #111 with #92 while it doesn't with this PR ;)
On the real side though you are right. But I honestly don't think that #92 will be done anytime soonish.

**Comment by main--** [comment]
>I honestly don't think that #92 will be done anytime soonish.

But it *is* done!

Keys getting stuck on the host is the big unresolved issue. But with the exception of that, all remaining tasks are trivial.

**Comment by main--** [comment]
#92 is coming along well, so closing this.

**Pull request closed without merging**
