### PR TITLE
Simple clipboard sharing

### PR DESCRIPTION
**Pull request by moritzuehling**
**Add `xorg-dev` to aur package.**

### CODE REVIEW

**Review by main-- — APPROVED** [review]
* the dependencies are frightening
* allowing the client to set our clipboard at any point might be a little insecure but I guess this should be fine (although a config option to turn it off would be nice of course)

Rest is looking good!

**Comment by main--** [comment]
Although, please figure out what exactly the dependency needs to be (if any). It's building right now on travis, so I'm not sure if we need anything at all or it's just installed by default for some reason.

**Comment by oberien** [comment]
> On Linux you need the x11 library, install it with something like:
> `sudo apt-get install xorg-dev`
>
> <cite>https://github.com/aweinstock314/rust-clipboard#prerequisites</cite>

**Comment by main--** [comment]
DANKE FÜR GAR NICHTS

**Pull request merged**
