### PR TITLE
Fixed wrong systemd exec binary path

### PR DESCRIPTION
**Pull request by Ediacarium**
You missed a spot over there

### CODE REVIEW

**Review by oberien — DISMISSED** [review]
lgtm

**Review by main-- — APPROVED** [review]

**Review by main-- — CHANGES_REQUESTED** [review]
On second thought, calling "run" would probably be best here.

**Comment by oberien** [comment]
A good point, you have.

**Review by oberien — APPROVED** [review]
It's called `run` duuuuuh Kappa

**Review by main-- — APPROVED** [review]

**Pull request merged**
